//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HELLION.Explorer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class HELLIONExplorer : global::System.Configuration.ApplicationSettingsBase {
        
        private static HELLIONExplorer defaultInstance = ((HELLIONExplorer)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HELLIONExplorer())));
        
        public static HELLIONExplorer Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sGameDataFolder {
            get {
                return ((string)(this["sGameDataFolder"]));
            }
            set {
                this["sGameDataFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sBlueprintsFolder {
            get {
                return ((string)(this["sBlueprintsFolder"]));
            }
            set {
                this["sBlueprintsFolder"] = value;
            }
        }
    }
}
