//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HELLION.Explorer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class HELLIONExplorer : global::System.Configuration.ApplicationSettingsBase {
        
        private static HELLIONExplorer defaultInstance = ((HELLIONExplorer)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HELLIONExplorer())));
        
        public static HELLIONExplorer Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sGameDataFolder {
            get {
                return ((string)(this["sGameDataFolder"]));
            }
            set {
                this["sGameDataFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bLoadCelestialBodiesFile {
            get {
                return ((bool)(this["bLoadCelestialBodiesFile"]));
            }
            set {
                this["bLoadCelestialBodiesFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CelestialBodies.json")]
        public string sCelestialBodiesFileName {
            get {
                return ((string)(this["sCelestialBodiesFileName"]));
            }
            set {
                this["sCelestialBodiesFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bLoadAsteroidsFile {
            get {
                return ((bool)(this["bLoadAsteroidsFile"]));
            }
            set {
                this["bLoadAsteroidsFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Asteroids.json")]
        public string sAsteroidsFileName {
            get {
                return ((string)(this["sAsteroidsFileName"]));
            }
            set {
                this["sAsteroidsFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bLoadStructuresFile {
            get {
                return ((bool)(this["bLoadStructuresFile"]));
            }
            set {
                this["bLoadStructuresFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Structures.json")]
        public string sStructuresFileName {
            get {
                return ((string)(this["sStructuresFileName"]));
            }
            set {
                this["sStructuresFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bLoadDynamicObjectsFile {
            get {
                return ((bool)(this["bLoadDynamicObjectsFile"]));
            }
            set {
                this["bLoadDynamicObjectsFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DynamicObjects.json")]
        public string sDynamicObjectsFile {
            get {
                return ((string)(this["sDynamicObjectsFile"]));
            }
            set {
                this["sDynamicObjectsFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bLoadModulesFile {
            get {
                return ((bool)(this["bLoadModulesFile"]));
            }
            set {
                this["bLoadModulesFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Modules,json")]
        public string sModulesFileName {
            get {
                return ((string)(this["sModulesFileName"]));
            }
            set {
                this["sModulesFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bLoadStationsFile {
            get {
                return ((bool)(this["bLoadStationsFile"]));
            }
            set {
                this["bLoadStationsFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Stations.json")]
        public string sStationsFileName {
            get {
                return ((string)(this["sStationsFileName"]));
            }
            set {
                this["sStationsFileName"] = value;
            }
        }
    }
}
