/* HEObjectTypesImageList.cs
 * CheeseJedi 2017
 * Defines an enum used to determine the index of a known image name
 * This definition needs to match the order of files presumably in alphabetical order
 */

 /// <summary>
 /// Note that this enum is critically related to:
 /// * HEUtilities.
 /// </summary>

namespace HELLION.DataStructures
{
    public enum HEObjectTypesImageList
    {
        a3DCameraOrbit_16x = 0,
        a3DExtrude_16x,
        a3DScene_16x,
        Actor_16x,
        Add_grey_16x,
        Alert_16x,
        Aserif_16x,
        Assembly_16x,
        Attribute_16x,
        AzureDefaultResource_16x,
        AzureLogicApp_16x,
        AzureLogicApp_color_16x,
        AzureResourceGroup_16x,
        AzureResourceTypeView_16x,
        AzureVirtualMachineExtension_16x,
        BalanceBrace_16x,
        BatchFile_16x,
        BehaviorAction_16x,
        Binary_16x,
        Bios_16x,
        BlankFile_16x,
        Bolt_16x,
        BranchRelationshipChild_16x,
        BranchRelationshipCousin_16x,
        BranchRelationshipGroup_16x,
        BranchRelationshipParent_16x,
        BranchRelationshipSibling_16x,
        BranchRelationship_16x,
        Branch_16x,
        Brightness_16x,
        BubbleChart_16x,
        Bug_16x,
        Builder_16x,
        BulletList_16x,
        ButtonIcon_16x,
        Callout_16x,
        CheckDot_16x,
        Checkerboard_16x,
        Collection_16x,
        ComponentDiagram_16x,
        Component_16x,
        Contrast_16x,
        CordovaMultidevice_16x,
        CSWorkflowDiagram_16x,
        DarkTheme_16x,
        DateTimeAxis_16x,
        Diagnose_16x,
        Dictionary_16x,
        Document_16x,
        DomainType_16x,
        Driver_16x,
        Ellipsis_16x,
        EndpointComponent_16x,
        Event_16x,
        Expander_16x,
        ExplodedPieChart_16x,
        FeedbackBubble_16x,
        FeedbackSad_16x,
        FeedbackSmile_16x,
        FileCollection_16x,
        FileError_16x,
        FileGroupError_16x,
        FileGroupWarning_16x,
        FileGroup_16x,
        FileOK_16x,
        FileWarning_16x,
        Filter_16x,
        FindResults_16x,
        Flag_16x,
        FolderError_16x,
        Folder_16x,
        Gauge_16x,
        HotSpot_16x,
        Hub_16x,
        JS_16x,
        Label_16x,
        ListFolder_16x,
        Marquee_16x,
        Numeric_16x,
        PermissionFile_16x,
        PieChart_16x,
        Property_16x,
        Rename_16x,
        SemanticZoom_16x,
        Settings_16x,
        Shader_16x,
        Share_16x,
        String_16x,
        Toolbox_16x,
        TreeView_16x,
    };


} // End of namespace HELLION
